package gaia.sdk.heimdall

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import java.util.Date

// AUTOGENERATED CLASS. DO NOT MODIFY.
abstract class HeimdallResponse {


data class HeimdallMutationResponse @JsonCreator constructor(
    @JsonProperty("data") val data: Data?,
    @JsonProperty("logs") val logs: Map<String, List<String>>?,
    @JsonProperty("errors") val errors: List<String>?): HeimdallResponse() {

    data class Data @JsonCreator constructor(        @JsonProperty("dispatchImpulse") val dispatchImpulse: Boolean?
        , @JsonProperty("dispatchImpulseContext") val dispatchImpulseContext: Boolean?
        , @JsonProperty("dispatchImpulseNotification") val dispatchImpulseNotification: Boolean?
        , @JsonProperty("dispatchImpulseLog") val dispatchImpulseLog: Boolean?
)
    }
}
