webhook-created: &webhook-created
  name: Webhook created
  command: |
    curl $BUILD_STATUS_URL\?flow\=circleci-created -d '{"repository":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_number":"'"$CIRCLE_BUILD_NUM"'","build_url":"'"$CIRCLE_BUILD_URL"'"}' -H "Content-Type: application/json" -X POST -i || true
webhook-failed: &webhook-failed
  name: Webhook completed
  when: on_fail
  command: |
    curl $BUILD_STATUS_URL\?flow\=circleci-completed\&status\=FAILED -d '{"repository":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_number":"'"$CIRCLE_BUILD_NUM"'","build_url":"'"$CIRCLE_BUILD_URL"'"}' -H "Content-Type: application/json" -X POST -i || true

version: 2.1
jobs:
  webhook-completed:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run:
          name: Webhook completed
          command: |
            curl $BUILD_STATUS_URL\?flow\=circleci-completed -d '{"repository":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"${CIRCLE_BRANCH:-${CIRCLE_TAG/-/\/}}"'","build_number":"'"$CIRCLE_PREVIOUS_BUILD_NUM"'","build_url":"'"$CIRCLE_BUILD_URL"'"}' -H "Content-Type: application/json" -X POST -i || true
  build-java:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"'
      TEST_RESULTS_PATH: build/circleci/test-results
    steps:
      - run:
          <<: *webhook-created
      - checkout
      - run: chmod a+x gradlew
      - restore_cache:
          key: cache-gradle-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - run: mkdir -p $TEST_RESULTS_PATH
      - run: ./gradlew test --stacktrace
      - run: find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} $TEST_RESULTS_PATH \;
      - run: ./gradlew assemble --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/circleci/test-results
      - run:
          <<: *webhook-failed
  build-javascript:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run:
          <<: *webhook-created
      - checkout
      - restore_cache:
          key: cache-node-{{ checksum "gaia-sdk-javascript/package.json" }}
      - run: cd ~/project/gaia-sdk-javascript && yarn install
      - save_cache:
          paths:
            - ./gaia-sdk-javascript/node_modules
          key: cache-node-{{ checksum "gaia-sdk-javascript/package.json" }}
      - run: cd ~/project/gaia-sdk-javascript && yarn test
      - run: cd ~/project/gaia-sdk-javascript && yarn build
      - run:
          <<: *webhook-failed
  release-java:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"'
    steps:
      - run:
          <<: *webhook-created
      - checkout
      - run: git config --local user.email "ci@leftshift.one" && git config --local user.name "Continuous Integration"
      - run: echo 'export SCOPE=${CIRCLE_TAG#trigger-release-}' >> $BASH_ENV && source $BASH_ENV
      - run: echo "Release scope is $SCOPE"
      - run: chmod a+x gradlew
      - run: ./gradlew test --stacktrace
      - run: ./gradlew final publish -Prelease.scope=$SCOPE --stacktrace
      - run:
          name: Cleanup release
          when: always
          command: git push -d origin $CIRCLE_TAG || true
      - run:
          <<: *webhook-failed
  release-javascript:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run:
          <<: *webhook-created
      - checkout
      - run: git config --local user.email "ci@leftshift.one" && git config --local user.name "Continuous Integration"
      - run: echo 'export SCOPE=${CIRCLE_TAG#trigger-release-}' >> $BASH_ENV && source $BASH_ENV
      - run: echo "Release scope is $SCOPE"
      - run: cd ~/project/gaia-sdk-javascript && npm install
      - run: cd ~/project/gaia-sdk-javascript && npm run test
      - run: npm set registry https://registry.npmjs.org/
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: cd ~/project/gaia-sdk-javascript && npm run release:$SCOPE
      - run:
          name: Cleanup release
          when: always
          command: git push -d origin $CIRCLE_TAG || true
      - run:
          <<: *webhook-failed

workflows:
  version: 2
  build:
    jobs:
      - build-java:
          filters:
            tags:
              ignore: /.*/
      - build-javascript:
          filters:
            tags:
              ignore: /.*/
      - webhook-completed:
          filters:
            tags:
              ignore: /.*/
          requires:
            - build-java
            - build-javascript
  release-major:
    jobs:
      - release-java:
          context: npm
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^trigger-release-(major|minor|patch)$/
      - release-javascript:
          context: npm
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^trigger-release-(major|minor|patch)$/
      - webhook-completed:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^trigger-release-(major|minor|patch)$/
          requires:
            - release-java
            - release-javascript
