import VariableRegistry from "../api/VariableRegistry";

// AUTOGENERATED CLASS. DO NOT MODIFY.
export abstract class RainRequest extends Array<(_:VariableRegistry) => string> {
    public static query(config:(_:RainQueryRequest) => void) {
        const request = new RainQueryRequest();
        config(request);
        return request;
    }
    public static mutation(config:(_:RainMutationRequest) => void) {
        const request = new RainMutationRequest();
        config(request);
        return request;
    }
    abstract getStatement():[string, {}];
}

export class RainQueryRequest extends RainRequest {
    public preprocessors:Array<string> = new Array<string>();

    public insights = (identityId:string, config:(_:QueryInsights) => void) => this.push((registry) => {
        const entity = new QueryInsights(identityId);
        config(entity);
        return entity.render(registry);
    });

    public getStatement = ():[string, {}] => {
        const registry = new VariableRegistry();
        const fields = this.map((e) => e(registry)).join(" ");
        const statement = `query rain(${registry.getDatatypes().join(", ")}) { ${fields} }`;
        return [statement, registry.getVariables()]
    }
}

class QueryInsights extends Array<(_:VariableRegistry) => string> {
    private identityId:string;

    constructor(identityId:string) {
        super();
        this.identityId = identityId;
    }

    public classify = (text:string, config:(_:QueryClassify) => void) => this.push((registry) => {
        const entity = new QueryClassify(text);
        config(entity);
        return entity.render(registry);
    });
    public gaiaQuery = (statement:string) => this.push((registry) => {
        const name1 = registry.register("statement", statement);
        return "gaiaQuery(statement:$" + name1 + ")";
    });

    public render = (registry:VariableRegistry): string => {
        const name1 = registry.register("identityId", this.identityId);
        return "insights(identityId:$" + name1 + ") { " + this.map((e) => e(registry)).join(" ") + " }";
    }
}

class QueryClassify extends Array<(_:VariableRegistry) => string> {
    private text:string;

    constructor(text:string) {
        super();
        this.text = text;
    }

    public qualifier = () => this.push(() => "qualifier");
    public reference = () => this.push(() => "reference");
    public score = () => this.push(() => "score");

    public render = (registry:VariableRegistry): string => {
        const name1 = registry.register("text", this.text);
        return "classify(text:$" + name1 + ") { " + this.map((e) => e(registry)).join(" ") + " }";
    }
}

export class RainMutationRequest extends RainRequest {
    public preprocessors:Array<string> = new Array<string>();

    public handleReception = (impulse:ReceptionImpulse) => this.push((registry) => {
        const name1 = registry.register("impulse", impulse);
        return "handleReception(impulse:$" + name1 + ")";
    });
    public handleUtterance = (impulse:UtteranceImpulse) => this.push((registry) => {
        const name1 = registry.register("impulse", impulse);
        return "handleUtterance(impulse:$" + name1 + ")";
    });
    public handleSuggestion = (impulse:SuggestionImpulse) => this.push((registry) => {
        const name1 = registry.register("impulse", impulse);
        return "handleSuggestion(impulse:$" + name1 + ")";
    });
    public handleButton = (impulse:ButtonImpulse) => this.push((registry) => {
        const name1 = registry.register("impulse", impulse);
        return "handleButton(impulse:$" + name1 + ")";
    });
    public handleSubmit = (impulse:SubmitImpulse) => this.push((registry) => {
        const name1 = registry.register("impulse", impulse);
        return "handleSubmit(impulse:$" + name1 + ")";
    });

    public getStatement = ():[string, {}] => {
        const registry = new VariableRegistry();
        const fields = this.map((e) => e(registry)).join(" ");
        const statement = `mutation rain(${registry.getDatatypes().join(", ")}) { ${fields} }`;
        return [statement, registry.getVariables()]
    }
}

export class ReceptionImpulse {
    identityId?: string;
    clientId?: string;
    userId?: string;
    attributes?: Map<String, any>;
}
export class ButtonImpulse {
    identityId?: string;
    clientId?: string;
    userId?: string;
    attributes?: Map<String, any>;
}
export class SubmitImpulse {
    identityId?: string;
    clientId?: string;
    userId?: string;
    attributes?: Map<String, any>;
}
export class SuggestionImpulse {
    identityId?: string;
    clientId?: string;
    userId?: string;
    attributes?: Map<String, any>;
}
export class UtteranceImpulse {
    identityId?: string;
    clientId?: string;
    userId?: string;
    payload?: string;
}
