import {ClientOptions} from '../api/ClientOptions';
import {ITransporter} from '../api/ITransporter';
import {AtlasQueryRequest} from './AtlasRequest';
import {AtlasQueryResponse} from './AtlasResponse';

// AUTOGENERATED CLASS. DO NOT MODIFY.
export class AtlasClient {
    private options: ClientOptions;
    private transporter: ITransporter;
    private nonce = Math.random();

    constructor(options: ClientOptions, transporter: ITransporter) {
        this.options = options;
        this.transporter = transporter;
    }

    public queryNative(statement: string, variables: Record<string, any> = {}, preprocessors: Array<string> = []): Promise<AtlasQueryResponse> {        this.nonce += 1;        const body = {            statement,            variables,            preprocessors,            timestamp: new Date().getTime(),            nonce: this.nonce,        };        return this.transporter.transport(this.options, body);    }
    public query(request: AtlasQueryRequest): Promise<AtlasQueryResponse> {
        const [statement, variables] = request.getStatement();
        return this.queryNative(statement, variables, request.preprocessors);
    }

}
