from api.client_options import ClientOptions
from api.transporter.http_transport import HttpTransport
from rain.RainClient import RainClient

"""
AUTOGENERATED CLASS. DO NOT MODIFY.
"""
class RainClientBuilder(object):

    @staticmethod
    def http(url):
        return RainClientBuilder(url)

    def __init__(self, url):
        self.url = url

    def with_apikey(self, apikey):
        self.apikey = apikey
        return self

    def with_secret(self, secret):
        self.secret = secret
        return self

    def build(self):
        return RainClient(HttpTransport(self.url, ClientOptions(self.apikey, self.secret)))
