package gaia.sdk.request.enumeration

enum class EdgeType {
    SUPERVISOR, 
    IDENTITY_NER_SKILL, 
    IDENTITY_ERROR_STATEMENT, 
    IDENTITY_UNKNOWN_BEHAVIOUR, 
    IDENTITY_DISCONTINUABLE_STATEMENT, 
    IDENTITY_WELCOME_BEHAVIOUR
}
