package gaia.sdk.rain

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import java.util.Date

// AUTOGENERATED CLASS. DO NOT MODIFY.
abstract class RainResponse {

data class RainQueryResponse @JsonCreator constructor(
    @JsonProperty("data") val data: Data?,
    @JsonProperty("logs") val logs: Map<String, List<String>>?,
    @JsonProperty("nluScore") val nluScore: Double?,
    @JsonProperty("nerScore") val nerScore: Double?,
    @JsonProperty("score") val score: Double?,
    @JsonProperty("errors") val errors: List<String>?): RainResponse() {

    data class Data @JsonCreator constructor(@JsonProperty("insights") val insights: Insights?
)    data class Insights @JsonCreator constructor(
        @JsonProperty("classify") val classify: Classify?, 
        @JsonProperty("gaiaQuery") val gaiaQuery: List<Map<String, Any>>?
    )

    data class Classify @JsonCreator constructor(
        @JsonProperty("qualifier") val qualifier: String?, 
        @JsonProperty("reference") val reference: String?, 
        @JsonProperty("score") val score: Float?
    )


    }

data class RainMutationResponse @JsonCreator constructor(
    @JsonProperty("data") val data: Data?,
    @JsonProperty("logs") val logs: Map<String, List<String>>?,
    @JsonProperty("errors") val errors: List<String>?): RainResponse() {

    data class Data @JsonCreator constructor(@JsonProperty("handleReception") val handleReception: Boolean?
, @JsonProperty("handleUtterance") val handleUtterance: Boolean?
, @JsonProperty("handleSuggestion") val handleSuggestion: Boolean?
, @JsonProperty("handleButton") val handleButton: Boolean?
, @JsonProperty("handleSubmit") val handleSubmit: Boolean?
)
    }
}
