package gaia.sdk.rain

import gaia.sdk.api.ClientOptions
import gaia.sdk.api.ITransporter
import gaia.sdk.support.HMAC
import gaia.sdk.transport.HttpTransport
import reactor.netty.http.client.HttpClient

// AUTOGENERATED CLASS. DO NOT MODIFY.
class RainClientBuilder private constructor(private val transporter: ITransporter) {

    lateinit var apiKey: String;
    lateinit var secret: String;

    companion object {
        @JvmStatic
        @JvmOverloads
        fun http(url: String, client: HttpClient = HttpClient.create()): RainClientBuilder {
            return RainClientBuilder(HttpTransport(url, client))
        }
        @JvmStatic
        fun custom(transporter: ITransporter): RainClientBuilder {
            return RainClientBuilder(transporter)
        }
    }

    fun withApiKey(key: String): RainClientBuilder {
        this.apiKey = key
        return this
    }

    fun withSecret(secret: String): RainClientBuilder {
        this.secret = secret
        return this
    }

    fun build(): RainClient {
        val options = ClientOptions(apiKey, HMAC(secret))
        return RainClient(options, transporter)
    }

}
