from enum import Enum


class EdgeType(Enum):
    SUPERVISOR = 1

    IDENTITY_NER_SKILL = 2

    IDENTITY_ERROR_STATEMENT = 3

    IDENTITY_UNKNOWN_BEHAVIOUR = 4

    IDENTITY_DISCONTINUABLE_STATEMENT = 5

    IDENTITY_WELCOME_BEHAVIOUR = 6

