import calendar
import itertools
import random
import time

from api.transporter.abstract_transporter import ITransporter
from heimdall.HeimdallRequest import HeimdallRequest
from heimdall.HeimdallResponse import HeimdallResponse

"""
AUTOGENERATED CLASS. DO NOT MODIFY.
"""
class HeimdallClient(object):

    def __init__(self, transporter: ITransporter):
        self.transporter = transporter
        self.counter = itertools.count(random.randint(0, 1000000))

    def execute_native(self, statement, variables, preprocessors):
        payload = {
            "statement": statement,
            "variables": variables,
            "timestamp": calendar.timegm(time.gmtime()),
            "nonce": self.counter.__next__(),
            "preprocessors": preprocessors
        }

        return HeimdallResponse(self.transporter.transport(payload))

    def execute(self, request:HeimdallRequest):
        statement = "query atlas($text: String!, $merge: Boolean!) { ver nlu(text: $text, merge: $merge) { " + (" ".join(request)) + "}}"
        variables = {"text": request.text, "merge": request.merge}

        return self.execute_native(statement, variables, [])
