from api.client_options import ClientOptions
from api.transporter.http_transport import HttpTransport
from heimdall.HeimdallClient import HeimdallClient

"""
AUTOGENERATED CLASS. DO NOT MODIFY.
"""
class HeimdallClientBuilder(object):

    @staticmethod
    def http(url):
        return HeimdallClientBuilder(url)

    def __init__(self, url):
        self.url = url

    def with_apikey(self, apikey):
        self.apikey = apikey
        return self

    def with_secret(self, secret):
        self.secret = secret
        return self

    def build(self):
        return HeimdallClient(HttpTransport(self.url, ClientOptions(self.apikey, self.secret)))
